namespace IsEnergyModel.XSD.DP_INFSOOB_1_981_00_05_01_01
{//------------------------------------------------------------------------------
    // <auto-generated>
    //     Этот код создан программой.
    //     Исполняемая версия:4.0.30319.17929
    //
    //     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
    //     повторной генерации кода.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // Этот исходный код был создан с помощью xsd, версия=4.0.30319.17929.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Файл
    {

        private ФайлДокумент документField;

        private string идФайлField;

        private string версПрогField;

        private ФайлВерсФорм версФормField;

        /// <remarks/>
        public ФайлДокумент Документ
        {
            get
            {
                return this.документField;
            }
            set
            {
                this.документField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдФайл
        {
            get
            {
                return this.идФайлField;
            }
            set
            {
                this.идФайлField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВерсПрог
        {
            get
            {
                return this.версПрогField;
            }
            set
            {
                this.версПрогField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлВерсФорм ВерсФорм
        {
            get
            {
                return this.версФормField;
            }
            set
            {
                this.версФормField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокумент
    {

        private ФайлДокументОперЭДО оперЭДОField;

        private ФайлДокументУчастЭДО участЭДОField;

        private ФайлДокументПодписант подписантField;

        private ФайлДокументКНД кНДField;

        private string кодНОField;

        /// <remarks/>
        public ФайлДокументОперЭДО ОперЭДО
        {
            get
            {
                return this.оперЭДОField;
            }
            set
            {
                this.оперЭДОField = value;
            }
        }

        /// <remarks/>
        public ФайлДокументУчастЭДО УчастЭДО
        {
            get
            {
                return this.участЭДОField;
            }
            set
            {
                this.участЭДОField = value;
            }
        }

        /// <remarks/>
        public ФайлДокументПодписант Подписант
        {
            get
            {
                return this.подписантField;
            }
            set
            {
                this.подписантField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументКНД КНД
        {
            get
            {
                return this.кНДField;
            }
            set
            {
                this.кНДField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодНО
        {
            get
            {
                return this.кодНОField;
            }
            set
            {
                this.кодНОField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументОперЭДО
    {

        private СертифТип[] сертифДолжнField;

        private string наимОргField;

        private string иННЮЛField;

        private string кППField;

        private string оГРНField;

        private string идОперЭДОField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СертифДолжн")]
        public СертифТип[] СертифДолжн
        {
            get
            {
                return this.сертифДолжнField;
            }
            set
            {
                this.сертифДолжнField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг
        {
            get
            {
                return this.наимОргField;
            }
            set
            {
                this.наимОргField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННЮЛ
        {
            get
            {
                return this.иННЮЛField;
            }
            set
            {
                this.иННЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КПП
        {
            get
            {
                return this.кППField;
            }
            set
            {
                this.кППField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОГРН
        {
            get
            {
                return this.оГРНField;
            }
            set
            {
                this.оГРНField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдОперЭДО
        {
            get
            {
                return this.идОперЭДОField;
            }
            set
            {
                this.идОперЭДОField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СертифТип
    {

        private ФИОТип фИОField;

        private string датаНачСертифField;

        private string датаКонСертифField;

        private string отпСертифField;

        private string сертификатField;

        /// <remarks/>
        public ФИОТип ФИО
        {
            get
            {
                return this.фИОField;
            }
            set
            {
                this.фИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаНачСертиф
        {
            get
            {
                return this.датаНачСертифField;
            }
            set
            {
                this.датаНачСертифField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаКонСертиф
        {
            get
            {
                return this.датаКонСертифField;
            }
            set
            {
                this.датаКонСертифField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОтпСертиф
        {
            get
            {
                return this.отпСертифField;
            }
            set
            {
                this.отпСертифField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Сертификат
        {
            get
            {
                return this.сертификатField;
            }
            set
            {
                this.сертификатField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФИОТип
    {

        private string фамилияField;

        private string имяField;

        private string отчествоField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Фамилия
        {
            get
            {
                return this.фамилияField;
            }
            set
            {
                this.фамилияField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Имя
        {
            get
            {
                return this.имяField;
            }
            set
            {
                this.имяField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Отчество
        {
            get
            {
                return this.отчествоField;
            }
            set
            {
                this.отчествоField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class АдрРФТип
    {

        private string индексField;

        private string кодРегионField;

        private string районField;

        private string городField;

        private string населПунктField;

        private string улицаField;

        private string домField;

        private string корпусField;

        private string квартField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Индекс
        {
            get
            {
                return this.индексField;
            }
            set
            {
                this.индексField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодРегион
        {
            get
            {
                return this.кодРегионField;
            }
            set
            {
                this.кодРегионField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Район
        {
            get
            {
                return this.районField;
            }
            set
            {
                this.районField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Город
        {
            get
            {
                return this.городField;
            }
            set
            {
                this.городField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаселПункт
        {
            get
            {
                return this.населПунктField;
            }
            set
            {
                this.населПунктField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Улица
        {
            get
            {
                return this.улицаField;
            }
            set
            {
                this.улицаField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Дом
        {
            get
            {
                return this.домField;
            }
            set
            {
                this.домField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Корпус
        {
            get
            {
                return this.корпусField;
            }
            set
            {
                this.корпусField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Кварт
        {
            get
            {
                return this.квартField;
            }
            set
            {
                this.квартField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументУчастЭДО
    {

        private object itemField;

        private СертифТип[] сертифДолжнField;

        private string идУчастЭДОField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ИП", typeof(ФайлДокументУчастЭДОИП))]
        [System.Xml.Serialization.XmlElementAttribute("ЮЛ", typeof(ФайлДокументУчастЭДОЮЛ))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СертифДолжн")]
        public СертифТип[] СертифДолжн
        {
            get
            {
                return this.сертифДолжнField;
            }
            set
            {
                this.сертифДолжнField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдУчастЭДО
        {
            get
            {
                return this.идУчастЭДОField;
            }
            set
            {
                this.идУчастЭДОField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументУчастЭДОИП
    {

        private АдрРФТип адрРФField;

        private ФИОТип фИОField;

        private string иННФЛField;

        private string оГРНИПField;

        private string датаПодклЭДОField;

        private string тлфField;

        /// <remarks/>
        public АдрРФТип АдрРФ
        {
            get
            {
                return this.адрРФField;
            }
            set
            {
                this.адрРФField = value;
            }
        }

        /// <remarks/>
        public ФИОТип ФИО
        {
            get
            {
                return this.фИОField;
            }
            set
            {
                this.фИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННФЛ
        {
            get
            {
                return this.иННФЛField;
            }
            set
            {
                this.иННФЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОГРНИП
        {
            get
            {
                return this.оГРНИПField;
            }
            set
            {
                this.оГРНИПField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаПодклЭДО
        {
            get
            {
                return this.датаПодклЭДОField;
            }
            set
            {
                this.датаПодклЭДОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Тлф
        {
            get
            {
                return this.тлфField;
            }
            set
            {
                this.тлфField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументУчастЭДОЮЛ
    {

        private АдрРФТип адрРФField;

        private ФИОТип фИООтвField;

        private string наимОргField;

        private string иННЮЛField;

        private string кППField;

        private string оГРНField;

        private string датаПодклЭДОField;

        private string тлфField;

        /// <remarks/>
        public АдрРФТип АдрРФ
        {
            get
            {
                return this.адрРФField;
            }
            set
            {
                this.адрРФField = value;
            }
        }

        /// <remarks/>
        public ФИОТип ФИООтв
        {
            get
            {
                return this.фИООтвField;
            }
            set
            {
                this.фИООтвField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг
        {
            get
            {
                return this.наимОргField;
            }
            set
            {
                this.наимОргField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННЮЛ
        {
            get
            {
                return this.иННЮЛField;
            }
            set
            {
                this.иННЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КПП
        {
            get
            {
                return this.кППField;
            }
            set
            {
                this.кППField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОГРН
        {
            get
            {
                return this.оГРНField;
            }
            set
            {
                this.оГРНField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаПодклЭДО
        {
            get
            {
                return this.датаПодклЭДОField;
            }
            set
            {
                this.датаПодклЭДОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Тлф
        {
            get
            {
                return this.тлфField;
            }
            set
            {
                this.тлфField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументПодписант
    {

        private ФИОТип фИОField;

        private string должностьField;

        /// <remarks/>
        public ФИОТип ФИО
        {
            get
            {
                return this.фИОField;
            }
            set
            {
                this.фИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Должность
        {
            get
            {
                return this.должностьField;
            }
            set
            {
                this.должностьField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ФайлДокументКНД
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1115109")]
        Item1115109,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ФайлВерсФорм
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5.01")]
        Item501,
    }
}