namespace IsEnergyModel.XSD.ON_SFAKT_1_897_01_05_01_03
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     Этот код создан программой.
    //     Исполняемая версия:4.0.30319.17929
    //
    //     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
    //     повторной генерации кода.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // Этот исходный код был создан с помощью xsd, версия=4.0.30319.17929.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Файл
    {

        private ФайлСвУчДокОбор свУчДокОборField;

        private ФайлДокумент документField;

        private string идФайлField;

        private string версПрогField;

        private ФайлВерсФорм версФормField;

        /// <remarks/>
        public ФайлСвУчДокОбор СвУчДокОбор
        {
            get
            {
                return this.свУчДокОборField;
            }
            set
            {
                this.свУчДокОборField = value;
            }
        }

        /// <remarks/>
        public ФайлДокумент Документ
        {
            get
            {
                return this.документField;
            }
            set
            {
                this.документField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдФайл
        {
            get
            {
                return this.идФайлField;
            }
            set
            {
                this.идФайлField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ВерсПрог
        {
            get
            {
                return this.версПрогField;
            }
            set
            {
                this.версПрогField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлВерсФорм ВерсФорм
        {
            get
            {
                return this.версФормField;
            }
            set
            {
                this.версФормField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлСвУчДокОбор
    {

        private ФайлСвУчДокОборСвОЭДОтпр свОЭДОтпрField;

        private string идОтпрField;

        private string идПокField;

        /// <remarks/>
        public ФайлСвУчДокОборСвОЭДОтпр СвОЭДОтпр
        {
            get
            {
                return this.свОЭДОтпрField;
            }
            set
            {
                this.свОЭДОтпрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдОтпр
        {
            get
            {
                return this.идОтпрField;
            }
            set
            {
                this.идОтпрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдПок
        {
            get
            {
                return this.идПокField;
            }
            set
            {
                this.идПокField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлСвУчДокОборСвОЭДОтпр
    {

        private string наимОргField;

        private string иННЮЛField;

        private string идЭДОField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг
        {
            get
            {
                return this.наимОргField;
            }
            set
            {
                this.наимОргField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННЮЛ
        {
            get
            {
                return this.иННЮЛField;
            }
            set
            {
                this.иННЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдЭДО
        {
            get
            {
                return this.идЭДОField;
            }
            set
            {
                this.идЭДОField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СумНДСТип
    {

        private string сумНДСField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СумНДС
        {
            get
            {
                return this.сумНДСField;
            }
            set
            {
                this.сумНДСField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СумАкцизТип
    {

        private string сумАкцизField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СумАкциз
        {
            get
            {
                return this.сумАкцизField;
            }
            set
            {
                this.сумАкцизField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СвГрузОтпрПолТип
    {

        private СвГрузОтпрПолТипНаимГОП наимГОПField;

        private АдресТип адресField;

        /// <remarks/>
        public СвГрузОтпрПолТипНаимГОП НаимГОП
        {
            get
            {
                return this.наимГОПField;
            }
            set
            {
                this.наимГОПField = value;
            }
        }

        /// <remarks/>
        public АдресТип Адрес
        {
            get
            {
                return this.адресField;
            }
            set
            {
                this.адресField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СвГрузОтпрПолТипНаимГОП
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("НаимОрг", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ФИОИП", typeof(ФИОТип))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ФИОТип
    {

        private string фамилияField;

        private string имяField;

        private string отчествоField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Фамилия
        {
            get
            {
                return this.фамилияField;
            }
            set
            {
                this.фамилияField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Имя
        {
            get
            {
                return this.имяField;
            }
            set
            {
                this.имяField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Отчество
        {
            get
            {
                return this.отчествоField;
            }
            set
            {
                this.отчествоField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class АдресТип
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("АдрИно", typeof(АдрИноТип))]
        [System.Xml.Serialization.XmlElementAttribute("АдрРФ", typeof(АдрРФТип))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class АдрИноТип
    {

        private string кодСтрField;

        private string адрТекстField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодСтр
        {
            get
            {
                return this.кодСтрField;
            }
            set
            {
                this.кодСтрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string АдрТекст
        {
            get
            {
                return this.адрТекстField;
            }
            set
            {
                this.адрТекстField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class АдрРФТип
    {

        private string индексField;

        private string кодРегионField;

        private string районField;

        private string городField;

        private string населПунктField;

        private string улицаField;

        private string домField;

        private string корпусField;

        private string квартField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Индекс
        {
            get
            {
                return this.индексField;
            }
            set
            {
                this.индексField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодРегион
        {
            get
            {
                return this.кодРегионField;
            }
            set
            {
                this.кодРегионField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Район
        {
            get
            {
                return this.районField;
            }
            set
            {
                this.районField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Город
        {
            get
            {
                return this.городField;
            }
            set
            {
                this.городField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаселПункт
        {
            get
            {
                return this.населПунктField;
            }
            set
            {
                this.населПунктField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Улица
        {
            get
            {
                return this.улицаField;
            }
            set
            {
                this.улицаField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Дом
        {
            get
            {
                return this.домField;
            }
            set
            {
                this.домField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Корпус
        {
            get
            {
                return this.корпусField;
            }
            set
            {
                this.корпусField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Кварт
        {
            get
            {
                return this.квартField;
            }
            set
            {
                this.квартField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class СвПродПокТип
    {

        private СвПродПокТипИдСв идСвField;

        private АдресТип адресField;

        /// <remarks/>
        public СвПродПокТипИдСв ИдСв
        {
            get
            {
                return this.идСвField;
            }
            set
            {
                this.идСвField = value;
            }
        }

        /// <remarks/>
        public АдресТип Адрес
        {
            get
            {
                return this.адресField;
            }
            set
            {
                this.адресField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СвПродПокТипИдСв
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвФЛ", typeof(СвПродПокТипИдСвСвФЛ))]
        [System.Xml.Serialization.XmlElementAttribute("СвЮЛ", typeof(СвПродПокТипИдСвСвЮЛ))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СвПродПокТипИдСвСвФЛ
    {

        private ФИОТип фИОИПField;

        private string иННФЛField;

        /// <remarks/>
        public ФИОТип ФИОИП
        {
            get
            {
                return this.фИОИПField;
            }
            set
            {
                this.фИОИПField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННФЛ
        {
            get
            {
                return this.иННФЛField;
            }
            set
            {
                this.иННФЛField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class СвПродПокТипИдСвСвЮЛ
    {

        private string наимОргField;

        private string иННЮЛField;

        private string кППField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимОрг
        {
            get
            {
                return this.наимОргField;
            }
            set
            {
                this.наимОргField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННЮЛ
        {
            get
            {
                return this.иННЮЛField;
            }
            set
            {
                this.иННЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КПП
        {
            get
            {
                return this.кППField;
            }
            set
            {
                this.кППField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокумент
    {

        private ФайлДокументСвСчФакт свСчФактField;

        private ФайлДокументТаблСчФакт таблСчФактField;

        private ФайлДокументПодписант подписантField;

        private ФайлДокументКНД кНДField;

        /// <remarks/>
        public ФайлДокументСвСчФакт СвСчФакт
        {
            get
            {
                return this.свСчФактField;
            }
            set
            {
                this.свСчФактField = value;
            }
        }

        /// <remarks/>
        public ФайлДокументТаблСчФакт ТаблСчФакт
        {
            get
            {
                return this.таблСчФактField;
            }
            set
            {
                this.таблСчФактField = value;
            }
        }

        /// <remarks/>
        public ФайлДокументПодписант Подписант
        {
            get
            {
                return this.подписантField;
            }
            set
            {
                this.подписантField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументКНД КНД
        {
            get
            {
                return this.кНДField;
            }
            set
            {
                this.кНДField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвСчФакт
    {

        private ФайлДокументСвСчФактИспрСчФ испрСчФField;

        private СвПродПокТип свПродField;

        private ФайлДокументСвСчФактГрузОт грузОтField;

        private СвГрузОтпрПолТип грузПолучField;

        private ФайлДокументСвСчФактСвПРД[] свПРДField;

        private СвПродПокТип свПокупField;

        private ФайлДокументСвСчФактИнфПол инфПолField;

        private string номерСчФField;

        private string датаСчФField;

        private string кодОКВField;

        /// <remarks/>
        public ФайлДокументСвСчФактИспрСчФ ИспрСчФ
        {
            get
            {
                return this.испрСчФField;
            }
            set
            {
                this.испрСчФField = value;
            }
        }

        /// <remarks/>
        public СвПродПокТип СвПрод
        {
            get
            {
                return this.свПродField;
            }
            set
            {
                this.свПродField = value;
            }
        }

        /// <remarks/>
        public ФайлДокументСвСчФактГрузОт ГрузОт
        {
            get
            {
                return this.грузОтField;
            }
            set
            {
                this.грузОтField = value;
            }
        }

        /// <remarks/>
        public СвГрузОтпрПолТип ГрузПолуч
        {
            get
            {
                return this.грузПолучField;
            }
            set
            {
                this.грузПолучField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СвПРД")]
        public ФайлДокументСвСчФактСвПРД[] СвПРД
        {
            get
            {
                return this.свПРДField;
            }
            set
            {
                this.свПРДField = value;
            }
        }

        /// <remarks/>
        public СвПродПокТип СвПокуп
        {
            get
            {
                return this.свПокупField;
            }
            set
            {
                this.свПокупField = value;
            }
        }

        /// <remarks/>
        public ФайлДокументСвСчФактИнфПол ИнфПол
        {
            get
            {
                return this.инфПолField;
            }
            set
            {
                this.инфПолField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерСчФ
        {
            get
            {
                return this.номерСчФField;
            }
            set
            {
                this.номерСчФField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаСчФ
        {
            get
            {
                return this.датаСчФField;
            }
            set
            {
                this.датаСчФField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string КодОКВ
        {
            get
            {
                return this.кодОКВField;
            }
            set
            {
                this.кодОКВField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвСчФактИспрСчФ
    {

        private string номИспрСчФField;

        private string датаИспрСчФField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомИспрСчФ
        {
            get
            {
                return this.номИспрСчФField;
            }
            set
            {
                this.номИспрСчФField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаИспрСчФ
        {
            get
            {
                return this.датаИспрСчФField;
            }
            set
            {
                this.датаИспрСчФField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвСчФактГрузОт
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ГрузОтпр", typeof(СвГрузОтпрПолТип))]
        [System.Xml.Serialization.XmlElementAttribute("ОнЖе", typeof(ФайлДокументСвСчФактГрузОтОнЖе))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ФайлДокументСвСчФактГрузОтОнЖе
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("он же")]
        онже,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвСчФактСвПРД
    {

        private string номерПРДField;

        private string датаПРДField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НомерПРД
        {
            get
            {
                return this.номерПРДField;
            }
            set
            {
                this.номерПРДField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ДатаПРД
        {
            get
            {
                return this.датаПРДField;
            }
            set
            {
                this.датаПРДField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументСвСчФактИнфПол
    {

        private string текстИнфField;

        private string идФайлИнфПолField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ТекстИнф
        {
            get
            {
                return this.текстИнфField;
            }
            set
            {
                this.текстИнфField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИдФайлИнфПол
        {
            get
            {
                return this.идФайлИнфПолField;
            }
            set
            {
                this.идФайлИнфПолField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументТаблСчФакт
    {

        private ФайлДокументТаблСчФактСведТов[] сведТовField;

        private ФайлДокументТаблСчФактВсегоОпл всегоОплField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("СведТов")]
        public ФайлДокументТаблСчФактСведТов[] СведТов
        {
            get
            {
                return this.сведТовField;
            }
            set
            {
                this.сведТовField = value;
            }
        }

        /// <remarks/>
        public ФайлДокументТаблСчФактВсегоОпл ВсегоОпл
        {
            get
            {
                return this.всегоОплField;
            }
            set
            {
                this.всегоОплField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументТаблСчФактСведТов
    {

        private СумАкцизТип акцизField;

        private ФайлДокументТаблСчФактСведТовНалСт налСтField;

        private СумНДСТип сумНалField;

        private string[] кодПроисхField;

        private string[] номерТДField;

        private string номСтрField;

        private string наимТовField;

        private string оКЕИ_ТовField;

        private decimal колТовField;

        private bool колТовFieldSpecified;

        private decimal ценаТовField;

        private bool ценаТовFieldSpecified;

        private decimal стТовБезНДСField;

        private bool стТовБезНДСFieldSpecified;

        private decimal стТовУчНалField;

        private string инфПолСтрField;

        /// <remarks/>
        public СумАкцизТип Акциз
        {
            get
            {
                return this.акцизField;
            }
            set
            {
                this.акцизField = value;
            }
        }

        /// <remarks/>
        public ФайлДокументТаблСчФактСведТовНалСт НалСт
        {
            get
            {
                return this.налСтField;
            }
            set
            {
                this.налСтField = value;
            }
        }

        /// <remarks/>
        public СумНДСТип СумНал
        {
            get
            {
                return this.сумНалField;
            }
            set
            {
                this.сумНалField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("КодПроисх")]
        public string[] КодПроисх
        {
            get
            {
                return this.кодПроисхField;
            }
            set
            {
                this.кодПроисхField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("НомерТД")]
        public string[] НомерТД
        {
            get
            {
                return this.номерТДField;
            }
            set
            {
                this.номерТДField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string НомСтр
        {
            get
            {
                return this.номСтрField;
            }
            set
            {
                this.номСтрField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string НаимТов
        {
            get
            {
                return this.наимТовField;
            }
            set
            {
                this.наимТовField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ОКЕИ_Тов
        {
            get
            {
                return this.оКЕИ_ТовField;
            }
            set
            {
                this.оКЕИ_ТовField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal КолТов
        {
            get
            {
                return this.колТовField;
            }
            set
            {
                this.колТовField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool КолТовSpecified
        {
            get
            {
                return this.колТовFieldSpecified;
            }
            set
            {
                this.колТовFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ЦенаТов
        {
            get
            {
                return this.ценаТовField;
            }
            set
            {
                this.ценаТовField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ЦенаТовSpecified
        {
            get
            {
                return this.ценаТовFieldSpecified;
            }
            set
            {
                this.ценаТовFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СтТовБезНДС
        {
            get
            {
                return this.стТовБезНДСField;
            }
            set
            {
                this.стТовБезНДСField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СтТовБезНДСSpecified
        {
            get
            {
                return this.стТовБезНДСFieldSpecified;
            }
            set
            {
                this.стТовБезНДСFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СтТовУчНал
        {
            get
            {
                return this.стТовУчНалField;
            }
            set
            {
                this.стТовУчНалField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИнфПолСтр
        {
            get
            {
                return this.инфПолСтрField;
            }
            set
            {
                this.инфПолСтрField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументТаблСчФактСведТовНалСт
    {

        private ФайлДокументТаблСчФактСведТовНалСтНалСтВел налСтВелField;

        private ФайлДокументТаблСчФактСведТовНалСтНалСтТип налСтТипField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументТаблСчФактСведТовНалСтНалСтВел НалСтВел
        {
            get
            {
                return this.налСтВелField;
            }
            set
            {
                this.налСтВелField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ФайлДокументТаблСчФактСведТовНалСтНалСтТип НалСтТип
        {
            get
            {
                return this.налСтТипField;
            }
            set
            {
                this.налСтТипField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ФайлДокументТаблСчФактСведТовНалСтНалСтВел
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("18")]
        Item18,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20")]
        Item20,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10/110")]
        Item10110,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("18/118")]
        Item18118,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("без НДС")]
        безНДС,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ФайлДокументТаблСчФактСведТовНалСтНалСтТип
    {

        /// <remarks/>
        процент,

        /// <remarks/>
        дробь,

        /// <remarks/>
        текст,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументТаблСчФактВсегоОпл
    {

        private СумНДСТип сумНалВсегоField;

        private decimal стТовБезНДСВсегоField;

        private bool стТовБезНДСВсегоFieldSpecified;

        private decimal стТовУчНалВсегоField;

        /// <remarks/>
        public СумНДСТип СумНалВсего
        {
            get
            {
                return this.сумНалВсегоField;
            }
            set
            {
                this.сумНалВсегоField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СтТовБезНДСВсего
        {
            get
            {
                return this.стТовБезНДСВсегоField;
            }
            set
            {
                this.стТовБезНДСВсегоField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool СтТовБезНДСВсегоSpecified
        {
            get
            {
                return this.стТовБезНДСВсегоFieldSpecified;
            }
            set
            {
                this.стТовБезНДСВсегоFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal СтТовУчНалВсего
        {
            get
            {
                return this.стТовУчНалВсегоField;
            }
            set
            {
                this.стТовУчНалВсегоField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументПодписант
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ИП", typeof(ФайлДокументПодписантИП))]
        [System.Xml.Serialization.XmlElementAttribute("ЮЛ", typeof(ФайлДокументПодписантЮЛ))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументПодписантИП
    {

        private ФИОТип фИОField;

        private string иННФЛField;

        private string свГосРегИПField;

        /// <remarks/>
        public ФИОТип ФИО
        {
            get
            {
                return this.фИОField;
            }
            set
            {
                this.фИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННФЛ
        {
            get
            {
                return this.иННФЛField;
            }
            set
            {
                this.иННФЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string СвГосРегИП
        {
            get
            {
                return this.свГосРегИПField;
            }
            set
            {
                this.свГосРегИПField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ФайлДокументПодписантЮЛ
    {

        private ФИОТип фИОField;

        private string иННЮЛField;

        private string должнField;

        /// <remarks/>
        public ФИОТип ФИО
        {
            get
            {
                return this.фИОField;
            }
            set
            {
                this.фИОField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ИННЮЛ
        {
            get
            {
                return this.иННЮЛField;
            }
            set
            {
                this.иННЮЛField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Должн
        {
            get
            {
                return this.должнField;
            }
            set
            {
                this.должнField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ФайлДокументКНД
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1115101")]
        Item1115101,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum ФайлВерсФорм
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5.01")]
        Item501,
    }
}