//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsEnergyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.LegalEntities = new HashSet<LegalEntities>();
            this.PhysicalPersons = new HashSet<PhysicalPersons>();
            this.SoleTraders = new HashSet<SoleTraders>();
            this.SubscribersSubdivision = new HashSet<SubscribersSubdivision>();
        }
    
        public int IdAddress { get; set; }
        public int TypeAddress { get; set; }
        public string RF_Index { get; set; }
        public Nullable<int> RF_IdRegion { get; set; }
        public string RF_Area { get; set; }
        public string RF_City { get; set; }
        public string RF_localityCity { get; set; }
        public string RF_Street { get; set; }
        public string RF_Home { get; set; }
        public string RF_Housing { get; set; }
        public string RF_OfficeOrApartment { get; set; }
        public string OtherCountry_Address { get; set; }
        public Nullable<int> OtherCountry_IdCountry { get; set; }
        public string AddressShort { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual Regions Regions { get; set; }
        public virtual ICollection<LegalEntities> LegalEntities { get; set; }
        public virtual ICollection<PhysicalPersons> PhysicalPersons { get; set; }
        public virtual ICollection<SoleTraders> SoleTraders { get; set; }
        public virtual ICollection<SubscribersSubdivision> SubscribersSubdivision { get; set; }
    }
}
