//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsEnergyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public Documents()
        {
            this.RelateDocuments = new HashSet<RelateDocuments>();
            this.DocumentFlow = new HashSet<DocumentFlow>();
        }
    
        public int IdDocument { get; set; }
        public string NameDocument { get; set; }
        public int TypeDocument { get; set; }
        public System.DateTime DateSend { get; set; }
        public int State { get; set; }
        public string Comment { get; set; }
        public string IdentifierSubscriberSender { get; set; }
        public string IdentifierSubscriberReceiver { get; set; }
        public Nullable<int> idSubdivisionSender { get; set; }
        public Nullable<int> idSubdivisionReceiver { get; set; }
        public Nullable<bool> SignatureContractor { get; set; }
        public Nullable<System.DateTime> DateReceive { get; set; }
        public byte[] DataFile { get; set; }
        public string NameFile { get; set; }
    
        public virtual ICollection<RelateDocuments> RelateDocuments { get; set; }
        public virtual ICollection<DocumentFlow> DocumentFlow { get; set; }
    }
}
