//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsEnergyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IFNS
    {
        public IFNS()
        {
            this.LegalEntities = new HashSet<LegalEntities>();
            this.SoleTraders = new HashSet<SoleTraders>();
        }
    
        public int IdIFNS { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> IdRegion { get; set; }
        public string Comment { get; set; }
        public string ShortName { get; set; }
    
        public virtual ICollection<LegalEntities> LegalEntities { get; set; }
        public virtual ICollection<SoleTraders> SoleTraders { get; set; }
    }
}
