//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsEnergyModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Is_EnergyEntities : DbContext
    {
        public Is_EnergyEntities()
            : base("name=Is_EnergyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Address> Address { get; set; }
        public DbSet<Administrators> Administrators { get; set; }
        public DbSet<Certificates> Certificates { get; set; }
        public DbSet<Cities> Cities { get; set; }
        public DbSet<Countries> Countries { get; set; }
        public DbSet<IFNS> IFNS { get; set; }
        public DbSet<LegalEntities> LegalEntities { get; set; }
        public DbSet<Operators> Operators { get; set; }
        public DbSet<PhysicalPersons> PhysicalPersons { get; set; }
        public DbSet<Regions> Regions { get; set; }
        public DbSet<RelateDocuments> RelateDocuments { get; set; }
        public DbSet<SoleTraders> SoleTraders { get; set; }
        public DbSet<Subscribers> Subscribers { get; set; }
        public DbSet<SubscribersCodesEnergySales> SubscribersCodesEnergySales { get; set; }
        public DbSet<SubscribersCodesGridCompany> SubscribersCodesGridCompany { get; set; }
        public DbSet<SubscribersConnectEnergySales> SubscribersConnectEnergySales { get; set; }
        public DbSet<SubscribersConnectGridCompany> SubscribersConnectGridCompany { get; set; }
        public DbSet<SubscribersContracts> SubscribersContracts { get; set; }
        public DbSet<SubscribersEnumerator> SubscribersEnumerator { get; set; }
        public DbSet<SubscribersSubdivision> SubscribersSubdivision { get; set; }
        public DbSet<SubscribersUserList> SubscribersUserList { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<SubscribesLog> SubscribesLog { get; set; }
        public DbSet<Documents> Documents { get; set; }
        public DbSet<DocumentsTemp> DocumentsTemp { get; set; }
        public DbSet<DocumentFlow> DocumentFlow { get; set; }
        public DbSet<Contractors> Contractors { get; set; }
        public DbSet<Maquettes16> Maquettes16 { get; set; }
    }
}
