//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsEnergyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maquettes16
    {
        public int IdMaquette16 { get; set; }
        public string NameDocument { get; set; }
        public int TypeDocument { get; set; }
        public int State { get; set; }
        public string NameFile { get; set; }
        public byte[] DataFile { get; set; }
        public byte[] DataFileObject { get; set; }
        public string IdentifierSubscriberES { get; set; }
        public Nullable<int> idSubdivisionES { get; set; }
        public Nullable<System.DateTime> DateSendES { get; set; }
        public string IdentifierSubscriberPC { get; set; }
        public Nullable<int> idSubdivisionPC { get; set; }
        public Nullable<System.DateTime> DateSendPC { get; set; }
        public string IdentifierSubscriberSK { get; set; }
        public Nullable<int> idSubdivisionSK { get; set; }
        public Nullable<System.DateTime> DateSendSK { get; set; }
        public Nullable<bool> SignatureContractor { get; set; }
        public string Comment { get; set; }
    }
}
