//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsEnergyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operators
    {
        public int IdOperator { get; set; }
        public int IdUser { get; set; }
        public bool MainOperator { get; set; }
        public bool ModifyingNews { get; set; }
        public bool ModifyingMailing { get; set; }
        public string Comment { get; set; }
        public string IdentifierSubscriber { get; set; }
    
        public virtual Subscribers Subscribers { get; set; }
        public virtual Users Users { get; set; }
    }
}
