//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsEnergyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelateDocuments
    {
        public int IdRelateDocument { get; set; }
        public int IdMainDocument { get; set; }
        public int Idchildren { get; set; }
        public string Comment { get; set; }
    
        public virtual Documents Documents { get; set; }
    }
}
