//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsEnergyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoleTraders
    {
        public int IdSoleTrader { get; set; }
        public Nullable<int> IdCertificate { get; set; }
        public string FirstName { get; set; }
        public string MidleName { get; set; }
        public string LastName { get; set; }
        public string INN { get; set; }
        public string OGRN { get; set; }
        public int IdIFNS { get; set; }
        public string ContactFaceFirstName { get; set; }
        public string ContactFaceMidleName { get; set; }
        public string ContactFaceLastName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string IdentifierSubscriber { get; set; }
        public Nullable<int> IdAddress { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual IFNS IFNS { get; set; }
        public virtual Subscribers Subscribers { get; set; }
        public virtual Certificates Certificates { get; set; }
    }
}
