//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsEnergyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscribesLog
    {
        public int IdSubscriberLog { get; set; }
        public string IdentifierSubscriber { get; set; }
        public int IdUserEditor { get; set; }
        public Nullable<System.DateTime> DateEdit { get; set; }
        public string TextEdit { get; set; }
        public string IdentifierSubscriberEditor { get; set; }
        public string NameSubscriberEditor { get; set; }
        public string NameUserEditor { get; set; }
    
        public virtual Subscribers Subscribers { get; set; }
    }
}
