//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsEnergyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscribersContracts
    {
        public SubscribersContracts()
        {
            this.SubscribersEnumerator = new HashSet<SubscribersEnumerator>();
        }
    
        public int IdContractSubscriber { get; set; }
        public string NumberContract { get; set; }
        public string Comment { get; set; }
        public string IdentifierSubscriber { get; set; }
    
        public virtual Subscribers Subscribers { get; set; }
        public virtual ICollection<SubscribersEnumerator> SubscribersEnumerator { get; set; }
    }
}
