//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsEnergyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscribersUserList
    {
        public int IdUsersList { get; set; }
        public int IdUser { get; set; }
        public bool Active { get; set; }
        public string Comment { get; set; }
        public int IdSubdivision { get; set; }
    
        public virtual SubscribersSubdivision SubscribersSubdivision { get; set; }
        public virtual Users Users { get; set; }
    }
}
