//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsEnergyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscribersSubdivision
    {
        public SubscribersSubdivision()
        {
            this.SubscribersCodesEnergySales = new HashSet<SubscribersCodesEnergySales>();
            this.SubscribersCodesGridCompany = new HashSet<SubscribersCodesGridCompany>();
            this.SubscribersUserList = new HashSet<SubscribersUserList>();
        }
    
        public int idSubdivision { get; set; }
        public string SubdivisionName { get; set; }
        public Nullable<int> IdParent { get; set; }
        public string Comment { get; set; }
        public string SubdivisionCode { get; set; }
        public string IdentifierSubscriber { get; set; }
        public Nullable<int> IdAddress { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Subscribers Subscribers { get; set; }
        public virtual ICollection<SubscribersCodesEnergySales> SubscribersCodesEnergySales { get; set; }
        public virtual ICollection<SubscribersCodesGridCompany> SubscribersCodesGridCompany { get; set; }
        public virtual ICollection<SubscribersUserList> SubscribersUserList { get; set; }
    }
}
