//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsEnergyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscribers
    {
        public Subscribers()
        {
            this.Administrators = new HashSet<Administrators>();
            this.LegalEntities = new HashSet<LegalEntities>();
            this.Operators = new HashSet<Operators>();
            this.PhysicalPersons = new HashSet<PhysicalPersons>();
            this.SoleTraders = new HashSet<SoleTraders>();
            this.SubscribersConnectEnergySales = new HashSet<SubscribersConnectEnergySales>();
            this.SubscribersConnectGridCompany = new HashSet<SubscribersConnectGridCompany>();
            this.SubscribersContracts = new HashSet<SubscribersContracts>();
            this.SubscribersSubdivision = new HashSet<SubscribersSubdivision>();
            this.SubscribesLog = new HashSet<SubscribesLog>();
            this.Contractors = new HashSet<Contractors>();
        }
    
        public string IdentifierSubscriber { get; set; }
        public int TypeElementAbonent { get; set; }
        public string Name { get; set; }
        public string Requisites { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> AccessFormalizedDocuments { get; set; }
        public Nullable<bool> AccessUnformalizedDocuments { get; set; }
        public Nullable<int> TypeGroupElectricity { get; set; }
        public Nullable<bool> AccessElectricityPrimaryDocuments { get; set; }
        public Nullable<bool> AccessElectricityForm80020 { get; set; }
        public Nullable<bool> AccessElectricityForm16 { get; set; }
        public Nullable<int> AccessFormalizedDocumentsAmount { get; set; }
        public Nullable<System.DateTime> AccessFormalizedDocumentsDateStart { get; set; }
        public Nullable<System.DateTime> AccessFormalizedDocumentsDateEnd { get; set; }
        public Nullable<int> AccessUnformalizedDocumentsAmount { get; set; }
        public Nullable<System.DateTime> AccessUnformalizedDocumentsDateStart { get; set; }
        public Nullable<System.DateTime> AccessUnformalizedDocumentsDateEnd { get; set; }
        public Nullable<System.DateTime> AccessElectricityPrimaryDocumentsDateStart { get; set; }
        public Nullable<System.DateTime> AccessElectricityPrimaryDocumentsDateEnd { get; set; }
        public Nullable<int> AccessElectricityForm80020Amount { get; set; }
        public Nullable<System.DateTime> AccessElectricityForm80020DateStart { get; set; }
        public Nullable<System.DateTime> AccessElectricityForm80020DateEnd { get; set; }
        public Nullable<int> AccessElectricityForm16Amount { get; set; }
        public Nullable<System.DateTime> AccessElectricityForm16DateStart { get; set; }
        public Nullable<System.DateTime> AccessElectricityForm16DateEnd { get; set; }
    
        public virtual ICollection<Administrators> Administrators { get; set; }
        public virtual ICollection<LegalEntities> LegalEntities { get; set; }
        public virtual ICollection<Operators> Operators { get; set; }
        public virtual ICollection<PhysicalPersons> PhysicalPersons { get; set; }
        public virtual ICollection<SoleTraders> SoleTraders { get; set; }
        public virtual ICollection<SubscribersConnectEnergySales> SubscribersConnectEnergySales { get; set; }
        public virtual ICollection<SubscribersConnectGridCompany> SubscribersConnectGridCompany { get; set; }
        public virtual ICollection<SubscribersContracts> SubscribersContracts { get; set; }
        public virtual ICollection<SubscribersSubdivision> SubscribersSubdivision { get; set; }
        public virtual ICollection<SubscribesLog> SubscribesLog { get; set; }
        public virtual ICollection<Contractors> Contractors { get; set; }
    }
}
