//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsEnergyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscribersConnectEnergySales
    {
        public int IdSubscribersConnectEnergySales { get; set; }
        public int idSubdivisionEnergySales { get; set; }
        public string Comment { get; set; }
        public string IdentifierSubscriber { get; set; }
    
        public virtual Subscribers Subscribers { get; set; }
    }
}
