//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsEnergyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Administrators = new HashSet<Administrators>();
            this.Operators = new HashSet<Operators>();
            this.SubscribersUserList = new HashSet<SubscribersUserList>();
            this.DocumentsTemp = new HashSet<DocumentsTemp>();
        }
    
        public int IdUser { get; set; }
        public string FirstName { get; set; }
        public string MidleName { get; set; }
        public string LastName { get; set; }
        public string Login { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Comment { get; set; }
        public Nullable<int> IdCertificate { get; set; }
        public string IdentifierSubscriberDefault { get; set; }
        public Nullable<bool> NoticesIncomingContractors { get; set; }
        public Nullable<bool> NoticesOutContractors { get; set; }
        public Nullable<bool> NoticesNews { get; set; }
        public Nullable<bool> NoticesEnergyConsumptionPrimaryDocuments { get; set; }
        public Nullable<bool> NoticesEnergyConsumptionMaquettes16 { get; set; }
        public Nullable<bool> NoticesEnergyConsumptionMaquettes80020 { get; set; }
        public Nullable<bool> NoticesInDoc { get; set; }
        public Nullable<bool> NoticesOutDoc { get; set; }
        public Nullable<bool> NoticesInMessages { get; set; }
        public Nullable<bool> NoticesOutMessages { get; set; }
    
        public virtual ICollection<Administrators> Administrators { get; set; }
        public virtual Certificates Certificates { get; set; }
        public virtual ICollection<Operators> Operators { get; set; }
        public virtual ICollection<SubscribersUserList> SubscribersUserList { get; set; }
        public virtual ICollection<DocumentsTemp> DocumentsTemp { get; set; }
    }
}
